# Some basic info about your company
company_name: Appiphany Ltd
from_email: support@appiphany.com.au
support_phone: 805-504-1126

# Your custom field label
custom_label: Dog or cat?

# Can customers attach files?
customer_attachments: true

# Where does your contact link go?
contact: http://www.appiphany.com.au/contact

# External links for the top nav section
nav_links:
    - Folio: http://www.appiphany.com.au/folio
    - company: http://www.appiphany.com.au/about
    - testimonials: http://www.appiphany.com.au/testimonials
    - contact: http://www.appiphany.com.au/contact
   